# Generated by Django 2.2.19 on 2023-10-20 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import proco.core.models
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_explore_api_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at',
                 proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('severity', models.CharField(
                    choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('CRITICAL', 'Critical')],
                    default='MEDIUM', max_length=20)),
                ('type',
                 models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('NOTIFICATION', 'Notification')],
                                  db_index=True, max_length=20)),
                ('sender', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient', jsonfield.fields.JSONField(default=list, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('subject_text', models.TextField(null=True)),
                ('message_text', models.TextField()),
                ('template', models.TextField(null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                 related_name='created_messages', to=settings.AUTH_USER_MODEL,
                                                 verbose_name='Created By')),
                ('last_modified_by',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                   related_name='updated_messages', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Last Updated By')),
            ],
            options={
                'ordering': ['last_modified_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMessage',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at',
                 proco.core.models.CustomDateTimeField(blank=True, editable=False, verbose_name='Last Updated Date')),
                ('created',
                 proco.core.models.CustomDateTimeField(blank=True, editable=False, verbose_name='Created Date')),
                ('severity', models.CharField(
                    choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('CRITICAL', 'Critical')],
                    default='MEDIUM', max_length=20)),
                ('type',
                 models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('NOTIFICATION', 'Notification')],
                                  db_index=True, max_length=20)),
                ('sender', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient', jsonfield.fields.JSONField(default=list, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('subject_text', models.TextField(null=True)),
                ('message_text', models.TextField()),
                ('template', models.TextField(null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                 on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                       on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                                       to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'historical message',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
