# Generated by Django 2.2.19 on 2023-11-02 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import proco.core.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_message_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDataSource',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', proco.core.models.CustomDateTimeField(blank=True, editable=False, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(blank=True, editable=False, verbose_name='Created Date')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Data Source Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('data_source_type', models.CharField(choices=[('SCHOOL_MASTER', 'School Master'), ('DAILY_CHECK_APP', 'Daily Check App'), ('QOS', 'QoS')], default='SCHOOL_MASTER', max_length=10, verbose_name='Data Source Type')),
                ('request_config', jsonfield.fields.JSONField(default=dict, null=True)),
                ('column_config', jsonfield.fields.JSONField(default=list, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'In Draft'), ('READY_TO_PUBLISH', 'Ready to Publish'), ('PUBLISHED', 'Published'), ('DISABLED', 'Disabled')], default='DRAFT', max_length=10)),
                ('published_at', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('published_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Published By')),
            ],
            options={
                'verbose_name': 'historical data source',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Data Source Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('data_source_type', models.CharField(choices=[('SCHOOL_MASTER', 'School Master'), ('DAILY_CHECK_APP', 'Daily Check App'), ('QOS', 'QoS')], default='SCHOOL_MASTER', max_length=10, verbose_name='Data Source Type')),
                ('request_config', jsonfield.fields.JSONField(default=dict, null=True)),
                ('column_config', jsonfield.fields.JSONField(default=list, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'In Draft'), ('READY_TO_PUBLISH', 'Ready to Publish'), ('PUBLISHED', 'Published'), ('DISABLED', 'Disabled')], default='DRAFT', max_length=10)),
                ('published_at', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_datasources', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_datasources', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_published_datasources', to=settings.AUTH_USER_MODEL, verbose_name='Published By')),
            ],
            options={
                'ordering': ['last_modified_at'],
            },
        ),
    ]
