# Generated by Django 2.2.19 on 2023-11-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_data_source_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='data_source_type',
            field=models.CharField(choices=[('SCHOOL_MASTER', 'School Master'), ('DAILY_CHECK_APP', 'Daily Check App'), ('QOS', 'QoS')], default='SCHOOL_MASTER', max_length=50, verbose_name='Data Source Type'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'In Draft'), ('READY_TO_PUBLISH', 'Ready to Publish'), ('PUBLISHED', 'Published'), ('DISABLED', 'Disabled')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldatasource',
            name='data_source_type',
            field=models.CharField(choices=[('SCHOOL_MASTER', 'School Master'), ('DAILY_CHECK_APP', 'Daily Check App'), ('QOS', 'QoS')], default='SCHOOL_MASTER', max_length=50, verbose_name='Data Source Type'),
        ),
        migrations.AlterField(
            model_name='historicaldatasource',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'In Draft'), ('READY_TO_PUBLISH', 'Ready to Publish'), ('PUBLISHED', 'Published'), ('DISABLED', 'Disabled')], default='DRAFT', max_length=50),
        ),
    ]
