# Generated by Django 2.2.19 on 2023-11-08 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import proco.core.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_data_source_model_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Layer Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('LIVE', 'Live'), ('STATIC', 'Static')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('CONNECTIVITY', 'Connectivity Layer Category'), ('COVERAGE', 'Coverage Layer Category')], default='CONNECTIVITY', max_length=20, verbose_name='Layer Category')),
                ('applicable_countries', jsonfield.fields.JSONField(default=list, null=True)),
                ('global_benchmark', jsonfield.fields.JSONField(default=dict, null=True)),
                ('legend_configs', jsonfield.fields.JSONField(default=list, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'In Draft'), ('READY_TO_PUBLISH', 'Ready to Publish'), ('PUBLISHED', 'Published'), ('DISABLED', 'Disabled')], default='DRAFT', max_length=20)),
                ('published_at', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_datalayers', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_datalayers', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='layer_published_datalayers', to=settings.AUTH_USER_MODEL, verbose_name='Published By')),
            ],
            options={
                'ordering': ['last_modified_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDataLayerDataSourceRelationship',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', proco.core.models.CustomDateTimeField(blank=True, editable=False, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(blank=True, editable=False, verbose_name='Created Date')),
                ('data_source_column', jsonfield.fields.JSONField(default=dict, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('data_layer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.DataLayer')),
                ('data_source', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.DataSource')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'historical data layer data source relationship',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDataLayer',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', proco.core.models.CustomDateTimeField(blank=True, editable=False, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(blank=True, editable=False, verbose_name='Created Date')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Layer Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('LIVE', 'Live'), ('STATIC', 'Static')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('CONNECTIVITY', 'Connectivity Layer Category'), ('COVERAGE', 'Coverage Layer Category')], default='CONNECTIVITY', max_length=20, verbose_name='Layer Category')),
                ('applicable_countries', jsonfield.fields.JSONField(default=list, null=True)),
                ('global_benchmark', jsonfield.fields.JSONField(default=dict, null=True)),
                ('legend_configs', jsonfield.fields.JSONField(default=list, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'In Draft'), ('READY_TO_PUBLISH', 'Ready to Publish'), ('PUBLISHED', 'Published'), ('DISABLED', 'Disabled')], default='DRAFT', max_length=20)),
                ('published_at', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('published_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Published By')),
            ],
            options={
                'verbose_name': 'historical data layer',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DataLayerDataSourceRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('data_source_column', jsonfield.fields.JSONField(default=dict, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_datalayerdatasourcerelationships', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('data_layer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_sources', to='accounts.DataLayer')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='layers', to='accounts.DataSource')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_datalayerdatasourcerelationships', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'ordering': ['last_modified_at'],
            },
        ),
    ]
