# Generated by Django 2.2.28 on 2024-02-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_data_layer_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='code',
            field=models.CharField(default='CODE', max_length=32),
        ),
        migrations.AddField(
            model_name='datalayer',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datalayer',
            name='is_reverse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapi',
            name='code',
            field=models.CharField(default='CODE', max_length=32),
        ),
        migrations.AddField(
            model_name='historicaldatalayer',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatalayer',
            name='is_reverse',
            field=models.BooleanField(default=False),
        ),
    ]
