# Generated by Django 2.2.28 on 2024-04-10 12:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import proco.core.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0018_added_soft_deletion_to_model'),
        ('accounts', '0007_updated_description_max_length_to_500'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDataLayerCountryRelationship',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at',
                 proco.core.models.CustomDateTimeField(blank=True, editable=False, verbose_name='Last Updated Date')),
                ('created',
                 proco.core.models.CustomDateTimeField(blank=True, editable=False, verbose_name='Created Date')),
                ('is_default', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('country', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                              on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                              to='locations.Country')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                 on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('data_layer', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                 on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                                 to='accounts.DataLayer')),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                       on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                                       to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'historical data layer country relationship',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DataLayerCountryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at',
                 proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('is_default', models.BooleanField(default=False)),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_layers',
                                   to='locations.Country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                 related_name='created_datalayercountryrelationships',
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('data_layer',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_countries',
                                   to='accounts.DataLayer')),
                ('last_modified_by',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                   related_name='updated_datalayercountryrelationships', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Last Updated By')),
            ],
            options={
                'ordering': ['last_modified_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='datalayercountryrelationship',
            constraint=models.UniqueConstraint(fields=('data_layer', 'country', 'deleted'), name='unique_with_deleted'),
        ),
        migrations.AddConstraint(
            model_name='datalayercountryrelationship',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('data_layer', 'country'),
                                               name='unique_without_deleted'),
        ),
    ]
