# Generated by Django 2.2.28 on 2024-04-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_datalayer_country_relationship_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='has_write_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apikey',
            name='write_access_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalapikey',
            name='has_write_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapikey',
            name='write_access_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
