# Generated by Django 2.2.28 on 2024-05-10 05:58

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_added_api_keys_write_access_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayercountryrelationship',
            name='data_sources',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatalayercountryrelationship',
            name='data_sources',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
    ]
