# Generated by Django 2.2.28 on 2024-05-27 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import proco.core.models
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0018_added_soft_deletion_to_model'),
        ('accounts', '0010_added_country_data_providers_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAPIKeyCountryRelationship',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at',
                 proco.core.models.CustomDateTimeField(blank=True, editable=False, verbose_name='Last Updated Date')),
                ('created',
                 proco.core.models.CustomDateTimeField(blank=True, editable=False, verbose_name='Created Date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('api_key', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                              on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                              to='accounts.APIKey')),
                ('country', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                              on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                              to='locations.Country')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                 on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                       on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                                       to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'historical api key country relationship',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='APIKeyCountryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at',
                 proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('api_key',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_countries',
                                   to='accounts.APIKey')),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_api_keys',
                                   to='locations.Country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                 related_name='created_apikeycountryrelationships',
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                   related_name='updated_apikeycountryrelationships', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Last Updated By')),
            ],
            options={
                'ordering': ['last_modified_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='apikeycountryrelationship',
            constraint=models.UniqueConstraint(fields=('api_key', 'country', 'deleted'),
                                               name='unique_with_deleted_for_api_key_country'),
        ),
        migrations.AddConstraint(
            model_name='apikeycountryrelationship',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('api_key', 'country'),
                                               name='unique_without_deleted_for_api_key_country'),
        ),
    ]
