# Generated by Django 2.2.28 on 2024-05-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_added_api_key_with_country_mapping_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalapikey',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
