# Generated by Django 2.2.28 on 2024-05-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0012_added_api_description_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(db_index=True, max_length=500, verbose_name='API Key Value'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='status',
            field=models.CharField(
                choices=[('INITIATED', 'Initiated'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], db_index=True,
                default='INITIATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='valid_to',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='API Key Valid Till Date'),
        ),
        migrations.AlterField(
            model_name='datalayer',
            name='status',
            field=models.CharField(
                choices=[('DRAFT', 'In Draft'), ('READY_TO_PUBLISH', 'Ready to Publish'), ('PUBLISHED', 'Published'),
                         ('DISABLED', 'Disabled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalapikey',
            name='api_key',
            field=models.CharField(db_index=True, max_length=500, verbose_name='API Key Value'),
        ),
        migrations.AlterField(
            model_name='historicalapikey',
            name='status',
            field=models.CharField(
                choices=[('INITIATED', 'Initiated'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], db_index=True,
                default='INITIATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalapikey',
            name='valid_to',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='API Key Valid Till Date'),
        ),
        migrations.AlterField(
            model_name='historicaldatalayer',
            name='status',
            field=models.CharField(
                choices=[('DRAFT', 'In Draft'), ('READY_TO_PUBLISH', 'Ready to Publish'), ('PUBLISHED', 'Published'),
                         ('DISABLED', 'Disabled')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
