# Generated by Django 2.2.28 on 2024-06-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_added_indexes_on_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='code',
            field=models.CharField(db_index=True, default='UNKNOWN', max_length=255, verbose_name='Layer Code'),
        ),
        migrations.AddField(
            model_name='historicaldatalayer',
            name='code',
            field=models.CharField(db_index=True, default='UNKNOWN', max_length=255, verbose_name='Layer Code'),
        ),
    ]
