# Generated by Django 2.2.28 on 2024-07-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_added_data_layer_code_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldatalayercountryrelationship',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicaldatalayercountryrelationship',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaldatalayercountryrelationship',
            name='data_layer',
        ),
        migrations.RemoveField(
            model_name='historicaldatalayercountryrelationship',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldatalayercountryrelationship',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='historicaldatalayerdatasourcerelationship',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaldatalayerdatasourcerelationship',
            name='data_layer',
        ),
        migrations.RemoveField(
            model_name='historicaldatalayerdatasourcerelationship',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='historicaldatalayerdatasourcerelationship',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldatalayerdatasourcerelationship',
            name='last_modified_by',
        ),
        migrations.DeleteModel(
            name='HistoricalAPIKeyCountryRelationship',
        ),
        migrations.DeleteModel(
            name='HistoricalDataLayerCountryRelationship',
        ),
        migrations.DeleteModel(
            name='HistoricalDataLayerDataSourceRelationship',
        ),
    ]
