# Generated by Django 2.2.28 on 2024-08-08 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import proco.core.models
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ('locations', '0019_added_country_data_source_description_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_deleted_unused_historical_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at',
                 proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('code', models.CharField(db_index=True, max_length=255, verbose_name='Filter Code')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Filter Name')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(
                    choices=[('DROPDOWN', 'Dropdown'), ('DROPDOWN_MULTISELECT', 'Dropdown with multi select'),
                             ('RANGE', 'Range'), ('INPUT', 'Input'), ('BOOLEAN', 'Boolean')], db_index=True,
                    max_length=50)),
                ('status', models.CharField(
                    choices=[('DRAFT', 'In Draft'), ('PUBLISHED', 'Activated'), ('DISABLED', 'De-activated')],
                    db_index=True, default='DRAFT', max_length=20)),
                ('published_at', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('options', jsonfield.fields.JSONField(default=dict, null=True)),
                ('query_param_filter', models.CharField(
                    choices=[('exact', 'Exact match'), ('iexact', 'Exact match by ignoring casing'),
                             ('contains', 'Contains value'), ('icontains', 'Contains value by ignoring casing'),
                             ('range', 'Inside range'), ('on', 'Yes/No choice'), ('in', 'In give list of values')],
                    default='iexact', max_length=20)),
            ],
            options={
                'ordering': ['last_modified_at'],
            },
        ),
        migrations.CreateModel(
            name='ColumnConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at',
                 proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Column DB Name')),
                ('label', models.CharField(db_index=True, max_length=100, verbose_name='Column UI Name')),
                ('type', models.CharField(
                    choices=[('int', 'Integer'), ('float', 'Float'), ('str', 'String'), ('boolean', 'Boolean')],
                    db_index=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('table_name', models.CharField(db_index=True, max_length=50, verbose_name='Table DB Name')),
                ('table_alias', models.CharField(db_index=True, max_length=100, verbose_name='Table Query Name')),
                ('table_label', models.CharField(db_index=True, max_length=100, verbose_name='Table UI Name')),
                ('is_filter_applicable', models.BooleanField(default=False)),
                ('options', jsonfield.fields.JSONField(default=dict, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                 related_name='created_columnconfigurations',
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                   related_name='updated_columnconfigurations', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Last Updated By')),
            ],
            options={
                'ordering': ['last_modified_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAdvanceFilter',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at',
                 proco.core.models.CustomDateTimeField(blank=True, editable=False, verbose_name='Last Updated Date')),
                ('created',
                 proco.core.models.CustomDateTimeField(blank=True, editable=False, verbose_name='Created Date')),
                ('code', models.CharField(db_index=True, max_length=255, verbose_name='Filter Code')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Filter Name')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(
                    choices=[('DROPDOWN', 'Dropdown'), ('DROPDOWN_MULTISELECT', 'Dropdown with multi select'),
                             ('RANGE', 'Range'), ('INPUT', 'Input'), ('BOOLEAN', 'Boolean')], db_index=True,
                    max_length=50)),
                ('status', models.CharField(
                    choices=[('DRAFT', 'In Draft'), ('PUBLISHED', 'Activated'), ('DISABLED', 'De-activated')],
                    db_index=True, default='DRAFT', max_length=20)),
                ('published_at', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('options', jsonfield.fields.JSONField(default=dict, null=True)),
                ('query_param_filter', models.CharField(
                    choices=[('exact', 'Exact match'), ('iexact', 'Exact match by ignoring casing'),
                             ('contains', 'Contains value'), ('icontains', 'Contains value by ignoring casing'),
                             ('range', 'Inside range'), ('on', 'Yes/No choice'), ('in', 'In give list of values')],
                    default='iexact', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('column_configuration', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                           on_delete=django.db.models.deletion.DO_NOTHING,
                                                           related_name='+', to='accounts.ColumnConfiguration')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                 on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                       on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                                       to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('published_by', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                   on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                                   to=settings.AUTH_USER_MODEL, verbose_name='Published By')),
            ],
            options={
                'verbose_name': 'historical advance filter',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AdvanceFilterCountryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at',
                 proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('advance_filter',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_countries',
                                   to='accounts.AdvanceFilter')),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_filters',
                                   to='locations.Country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                 related_name='created_advancefiltercountryrelationships',
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                   related_name='updated_advancefiltercountryrelationships',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'ordering': ['last_modified_at'],
            },
        ),
        migrations.AddField(
            model_name='advancefilter',
            name='column_configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filters',
                                    to='accounts.ColumnConfiguration'),
        ),
        migrations.AddField(
            model_name='advancefilter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='created_advancefilters', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='advancefilter',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='updated_advancefilters', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Last Updated By'),
        ),
        migrations.AddField(
            model_name='advancefilter',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='filter_published_advancefilters', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Published By'),
        ),
        migrations.AddConstraint(
            model_name='advancefiltercountryrelationship',
            constraint=models.UniqueConstraint(fields=('advance_filter', 'country', 'deleted'),
                                               name='unique_with_deleted_for_advance_filters_country'),
        ),
        migrations.AddConstraint(
            model_name='advancefiltercountryrelationship',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('advance_filter', 'country'),
                                               name='unique_without_deleted_for_advance_filters_country'),
        ),
        migrations.AddConstraint(
            model_name='advancefilter',
            constraint=models.UniqueConstraint(fields=('code', 'deleted'),
                                               name='unique_with_deleted_for_advance_filters'),
        ),
        migrations.AddConstraint(
            model_name='advancefilter',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('code',),
                                               name='unique_without_deleted_for_advance_filters'),
        ),
    ]
