# Generated by Django 2.2.28 on 2024-08-22 08:21

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_added_advance_filter_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayercountryrelationship',
            name='is_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datalayercountryrelationship',
            name='legend_configs',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
    ]
