# Generated by Django 2.2.28 on 2024-07-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_added_advance_filter_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancefilter',
            name='applicable_countries',
        ),
        migrations.RemoveField(
            model_name='advancefilter',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='historicaladvancefilter',
            name='applicable_countries',
        ),
        migrations.RemoveField(
            model_name='historicaladvancefilter',
            name='icon',
        ),
    ]
