# Generated by Django 2.2.28 on 2024-11-28 14:15

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_added_data_layer_legends_for_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayerdatasourcerelationship',
            name='data_source_column_function',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
    ]
