# Generated by Django 2.2.28 on 2024-08-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_added_dropdown_multiselect_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancefilter',
            name='type',
            field=models.CharField(choices=[('DROPDOWN', 'Dropdown'), ('DROPDOWN_MULTISELECT', 'Dropdown with multi select'), ('RANGE', 'Range'), ('INPUT', 'Input'), ('BOOLEAN', 'Boolean')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaladvancefilter',
            name='type',
            field=models.CharField(choices=[('DROPDOWN', 'Dropdown'), ('DROPDOWN_MULTISELECT', 'Dropdown with multi select'), ('RANGE', 'Range'), ('INPUT', 'Input'), ('BOOLEAN', 'Boolean')], db_index=True, max_length=50),
        ),
    ]
