# Generated by Django 2.2.28 on 2025-03-18 06:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import proco.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0018_added_data_layer_column_function_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', proco.core.models.CustomDateTimeField(auto_now=True,
                                                                           verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='API Category Name')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='api_categories', to='accounts.API')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_apicategorys', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_apicategorys', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'ordering': ['last_modified_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAPICategory',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', proco.core.models.CustomDateTimeField(blank=True, editable=False, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(blank=True, editable=False, verbose_name='Created Date')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='API Category Name')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('api', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.API')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'historical api category',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='APIKeyAPICategoryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('api_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_api_keys', to='accounts.APICategory')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_categories', to='accounts.APIKey')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_apikeyapicategoryrelationships', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_apikeyapicategoryrelationships', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'ordering': ['last_modified_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='apikeyapicategoryrelationship',
            constraint=models.UniqueConstraint(fields=('api_key', 'api_category', 'deleted'), name='unique_with_deleted_for_api_key_api_category'),
        ),
        migrations.AddConstraint(
            model_name='apikeyapicategoryrelationship',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('api_key', 'api_category'), name='unique_without_deleted_for_api_key_api_category'),
        ),
        migrations.AddConstraint(
            model_name='apicategory',
            constraint=models.UniqueConstraint(fields=('code', 'deleted'), name='unique_with_deleted_for_api_category'),
        ),
        migrations.AddConstraint(
            model_name='apicategory',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('code',), name='unique_without_deleted_for_api_category'),
        ),
    ]
