# Generated by Django 2.2.28 on 2025-03-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_added_api_category_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicategory',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapicategory',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
