# Generated by Django 2.2.28 on 2025-04-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_added_is_default_api_category_option'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='api',
            constraint=models.UniqueConstraint(fields=('code', 'deleted'), name='unique_api_code_with_deleted'),
        ),
        migrations.AddConstraint(
            model_name='api',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('code',), name='unique_api_code_without_deleted'),
        ),
    ]
