# Generated by Django 2.2.28 on 2026-02-13 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('accounts', '0020_added_unique_constraint_on_api_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='entity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_layers', to='entities.EntityType'),
        ),
        migrations.AddField(
            model_name='historicaldatalayer',
            name='entity_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entities.EntityType'),
        ),
    ]
