# Generated by Django 2.2.28 on 2026-02-24 13:03

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_added_unique_constraint_on_api_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancefiltercountryrelationship',
            name='default_filter_values',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='advancefiltercountryrelationship',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
