# Generated by Django 2.2.28 on 2026-01-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_added_unique_constraint_on_api_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='entity_type',
            field=models.CharField(choices=[('school', 'School'), ('health', 'Health'), ('library', 'Library')], db_index=True, default='school', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldatalayer',
            name='entity_type',
            field=models.CharField(choices=[('school', 'School'), ('health', 'Health'), ('library', 'Library')], db_index=True, default='school', max_length=20),
        ),
    ]
