# Generated by Django 2.2.28 on 2025-08-25 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import proco.core.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_added_unique_constraint_on_api_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at',
                 proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('value_type', models.CharField(db_index=True, max_length=20, null=True)),
                ('description', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('min_value', models.CharField(max_length=100, null=True)),
                ('max_value', models.CharField(max_length=100, null=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_view', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                 related_name='created_appconfigurations', to=settings.AUTH_USER_MODEL,
                                                 verbose_name='Created By')),
                ('last_modified_by',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                   related_name='updated_appconfigurations', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Last Updated By')),
            ],
            options={
                'ordering': ['last_modified_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='appconfiguration',
            constraint=models.UniqueConstraint(fields=('name', 'value_type', 'deleted'),
                                               name='unique_with_deleted_for_app_configurations'),
        ),
        migrations.AddConstraint(
            model_name='appconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('name', 'value_type'),
                                               name='unique_without_deleted_for_app_configurations'),
        ),
    ]
