# Generated by Django 2.2.28 on 2026-03-26 07:24

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20260224_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayerdatasourcerelationship',
            name='data_source_column_function',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
    ]
