# Generated by Django 2.2.28 on 2026-02-18 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('accounts', '0021_auto_20260213_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancefilter',
            name='entity_type',
            field=models.ForeignKey(blank=True, help_text='Entity type this filter applies to. NULL means legacy school-only.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='advance_filters', to='entities.EntityType'),
        ),
        migrations.AddField(
            model_name='columnconfiguration',
            name='entity_type',
            field=models.ForeignKey(blank=True, help_text='Entity type this column configuration applies to. NULL means legacy school-only.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='column_configurations', to='entities.EntityType'),
        ),
        migrations.AddField(
            model_name='historicaladvancefilter',
            name='entity_type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Entity type this filter applies to. NULL means legacy school-only.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entities.EntityType'),
        ),
    ]
