# Generated by Django 2.2.28 on 2026-08-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('accounts', '0022_datalayerdatasourcerelationship_data_source_column_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancefilter',
            name='entity_type',
            field=models.ForeignKey(blank=True, help_text='Entity type this filter applies to. NULL means legacy school-only.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='advance_filters', to='entities.EntityType'),
        ),
        migrations.AddField(
            model_name='columnconfiguration',
            name='entity_type',
            field=models.ForeignKey(blank=True, help_text='Entity type this column configuration applies to. NULL means legacy school-only.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='column_configurations', to='entities.EntityType'),
        ),
        migrations.AddField(
            model_name='datalayer',
            name='entity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_layers', to='entities.EntityType'),
        ),
        migrations.AddField(
            model_name='historicaladvancefilter',
            name='entity_type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Entity type this filter applies to. NULL means legacy school-only.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entities.EntityType'),
        ),
        migrations.AddField(
            model_name='historicaldatalayer',
            name='entity_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entities.EntityType'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='data_source_type',
            field=models.CharField(choices=[('SCHOOL_MASTER', 'School Master'), ('DAILY_CHECK_APP', 'Daily Check App'), ('QOS', 'QoS'), ('HEALTH_MASTER', 'Health Master')], default='SCHOOL_MASTER', max_length=50, verbose_name='Data Source Type'),
        ),
        migrations.AlterField(
            model_name='historicaldatasource',
            name='data_source_type',
            field=models.CharField(choices=[('SCHOOL_MASTER', 'School Master'), ('DAILY_CHECK_APP', 'Daily Check App'), ('QOS', 'QoS'), ('HEALTH_MASTER', 'Health Master')], default='SCHOOL_MASTER', max_length=50, verbose_name='Data Source Type'),
        ),
    ]
