# Generated by Django 2.2.28 on 2026-03-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20260218_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='data_source_type',
            field=models.CharField(choices=[('SCHOOL_MASTER', 'School Master'), ('DAILY_CHECK_APP', 'Daily Check App'), ('QOS', 'QoS'), ('HEALTH_MASTER', 'Health Master')], default='SCHOOL_MASTER', max_length=50, verbose_name='Data Source Type'),
        ),
        migrations.AlterField(
            model_name='historicaldatasource',
            name='data_source_type',
            field=models.CharField(choices=[('SCHOOL_MASTER', 'School Master'), ('DAILY_CHECK_APP', 'Daily Check App'), ('QOS', 'QoS'), ('HEALTH_MASTER', 'Health Master')], default='SCHOOL_MASTER', max_length=50, verbose_name='Data Source Type'),
        ),
    ]
