# Generated by Django 2.2.19 on 2023-11-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0008_auth_model_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrolepermission',
            name='slug',
            field=models.CharField(choices=[('can_view_country', 'Can View All Countries'), ('can_add_country', 'Can Add a Country'), ('can_update_country', 'Can Update a Country'), ('can_delete_country', 'Can Delete a Country'), ('can_view_user', 'Can View User'), ('can_add_user', 'Can Add User'), ('can_view_all_roles', 'Can View All Roles'), ('can_update_user_role', 'Can Update User Role'), ('can_view_role_configurations', 'Can View Role Configurations'), ('can_create_role_configurations', 'Can Create Role Configurations'), ('can_update_role_configurations', 'Can Update Role Configurations'), ('can_delete_role_configurations', 'Can Delete Role Configurations'), ('can_access_users_tab', 'Can Access User Management Tab'), ('can_delete_user', 'Can Delete a User'), ('can_update_user', 'Can Update a User'), ('can_add_user_relation', 'Can Add a New User Relation'), ('can_delete_user_relation', 'Can Delete a New User Relation'), ('can_update_user_relation', 'Can Add a New User Relation'), ('can_view_app_config', 'Can View App Configurations'), ('can_update_app_config', 'Can Update App Configurations'), ('can_view_notification', 'Can View Notification'), ('can_create_notification', 'Can Create Notification'), ('can_delete_notification', 'Can Delete Notification'), ('can_view_data_layer', 'Can View Data Layer'), ('can_add_data_layer', 'Can Add Data Layer'), ('can_delete_data_layer', 'Can Delete Data Layer'), ('can_update_data_layer', 'Can Update Data Layer'), ('can_publish_data_layer', 'Can Publish Data Layer'), ('can_view_data_source', 'Can View Data Source'), ('can_add_data_source', 'Can Add Data Source'), ('can_delete_data_source', 'Can Delete Data Source'), ('can_update_data_source', 'Can Update Data Source'), ('can_publish_data_source', 'Can Publish Data Source')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='slug',
            field=models.CharField(choices=[('can_view_country', 'Can View All Countries'), ('can_add_country', 'Can Add a Country'), ('can_update_country', 'Can Update a Country'), ('can_delete_country', 'Can Delete a Country'), ('can_view_user', 'Can View User'), ('can_add_user', 'Can Add User'), ('can_view_all_roles', 'Can View All Roles'), ('can_update_user_role', 'Can Update User Role'), ('can_view_role_configurations', 'Can View Role Configurations'), ('can_create_role_configurations', 'Can Create Role Configurations'), ('can_update_role_configurations', 'Can Update Role Configurations'), ('can_delete_role_configurations', 'Can Delete Role Configurations'), ('can_access_users_tab', 'Can Access User Management Tab'), ('can_delete_user', 'Can Delete a User'), ('can_update_user', 'Can Update a User'), ('can_add_user_relation', 'Can Add a New User Relation'), ('can_delete_user_relation', 'Can Delete a New User Relation'), ('can_update_user_relation', 'Can Add a New User Relation'), ('can_view_app_config', 'Can View App Configurations'), ('can_update_app_config', 'Can Update App Configurations'), ('can_view_notification', 'Can View Notification'), ('can_create_notification', 'Can Create Notification'), ('can_delete_notification', 'Can Delete Notification'), ('can_view_data_layer', 'Can View Data Layer'), ('can_add_data_layer', 'Can Add Data Layer'), ('can_delete_data_layer', 'Can Delete Data Layer'), ('can_update_data_layer', 'Can Update Data Layer'), ('can_publish_data_layer', 'Can Publish Data Layer'), ('can_view_data_source', 'Can View Data Source'), ('can_add_data_source', 'Can Add Data Source'), ('can_delete_data_source', 'Can Delete Data Source'), ('can_update_data_source', 'Can Update Data Source'), ('can_publish_data_source', 'Can Publish Data Source')], db_index=True, max_length=100),
        ),
    ]
