# Generated by Django 2.2.28 on 2024-07-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0013_updated_applicationuser_username_max_length_same_as_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserrolerelationship',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaluserrolerelationship',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaluserrolerelationship',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='historicaluserrolerelationship',
            name='role',
        ),
        migrations.RemoveField(
            model_name='historicaluserrolerelationship',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userrolerelationship',
            options={},
        ),
        migrations.DeleteModel(
            name='HistoricalRolePermission',
        ),
        migrations.DeleteModel(
            name='HistoricalUserRoleRelationship',
        ),
    ]
