FROM python:3.8-buster

# Install dependencies
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    build-essential \
    libcurl4-openssl-dev \
    libjpeg-dev \
    vim \
    ntp \
    libpq-dev
RUN apt-get install -y --no-install-recommends \
    git-core
RUN apt-get install -y --no-install-recommends \
    postgresql-client \
    libpq-dev \
    python-psycopg2
RUN apt-get install -y --no-install-recommends \
    python-gdal \
    gdal-bin \
    libgdal-dev \
    libgdal20 \
    libxml2-dev \
    libxslt-dev \
    xmlsec1

RUN pip install --upgrade \
    setuptools \
    pip \
    wheel \
    pipenv

RUN apt-get update && apt-get install -y \
    postgresql postgresql-contrib libpq-dev gcc \
    systemctl start postgresql.service

USER postgres
RUN sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'root';"
    
USER root
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add - \
    echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list \
    curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg \
    echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list \
    apt update \
    apt install postgis postgresql-14-postgis-3 \
    apt-get install redis \
    apt install binutils libproj-dev gdal-bin

# python app
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH /code

RUN mkdir /code

ADD Pipfile /code/Pipfile
ADD Pipfile.lock /code/Pipfile.lock

WORKDIR /code/

 # todo: try to figure out how we can test using dev packages and exclude them from prod build at the same time...
RUN pipenv install --ignore-pipfile --dev
RUN ./scripts/runtests.sh

ADD . /code/


