# Generated by Django 2.2.15 on 2020-09-03 08:30

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('connection_statistics', '0008_auto_20200903_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryweeklystatus',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 3, 8, 30, 30, 315764, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 3, 8, 30, 34, 100522, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
