# Generated by Django 2.2.16 on 2020-09-17 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0017_merge_20200915_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryweeklystatus',
            name='schools_with_data_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
