# Generated by Django 2.2.16 on 2020-09-22 09:24

import django.core.validators
from django.db import migrations, models

import calendar
from datetime import datetime, timedelta


class Migration(migrations.Migration):
    dependencies = [
        ('connection_statistics', '0018_countryweeklystatus_schools_with_data_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='schools_with_data_percentage',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=6,
                                      validators=[django.core.validators.MaxValueValidator(1),
                                                  django.core.validators.MinValueValidator(0)]),
        ),
    ]
