# Generated by Django 2.2.16 on 2020-09-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0020_auto_20200923_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydailystatus',
            name='connectivity_speed_in_bits',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='connectivity_speed_in_bits',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='connectivity_speed_in_bits',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='connectivity_speed_in_bits',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='connectivity_speed_in_bits',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='countrydailystatus',
            name='connectivity_speed',
        ),
        migrations.RemoveField(
            model_name='countryweeklystatus',
            name='connectivity_speed',
        ),
        migrations.RemoveField(
            model_name='realtimeconnectivity',
            name='connectivity_speed',
        ),
        migrations.RemoveField(
            model_name='schooldailystatus',
            name='connectivity_speed',
        ),
        migrations.RemoveField(
            model_name='schoolweeklystatus',
            name='connectivity_speed',
        ),
        migrations.RenameField(
            model_name='countrydailystatus',
            old_name='connectivity_speed_in_bits',
            new_name='connectivity_speed',
        ),
        migrations.RenameField(
            model_name='countryweeklystatus',
            old_name='connectivity_speed_in_bits',
            new_name='connectivity_speed',
        ),
        migrations.RenameField(
            model_name='realtimeconnectivity',
            old_name='connectivity_speed_in_bits',
            new_name='connectivity_speed',
        ),
        migrations.RenameField(
            model_name='schooldailystatus',
            old_name='connectivity_speed_in_bits',
            new_name='connectivity_speed',
        ),
        migrations.RenameField(
            model_name='schoolweeklystatus',
            old_name='connectivity_speed_in_bits',
            new_name='connectivity_speed',
        ),
    ]
