# Generated by Django 2.2.19 on 2023-11-28 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import proco.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_school_coverage_status_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connection_statistics', '0043_countryweeklystatus_global_connectivity_benchmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRealTimeRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('rt_registered', models.BooleanField(default=False)),
                ('rt_registration_date', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('rt_source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_schoolrealtimeregistrations', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_schoolrealtimeregistrations', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_registration_status', to='schools.School')),
            ],
            options={
                'verbose_name': 'School Real Time Registration Status',
                'verbose_name_plural': 'School Real Time Registration Data',
                'ordering': ('id',),
            },
        ),
    ]
