# Generated by Django 2.2.28 on 2024-01-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0044_school_rt_registration_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='download_speed_contracted',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='electricity_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='fiber_node_distance',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='microwave_node_distance',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='nearest_gsm_distance',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='nearest_lte_distance',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='nearest_umts_distance',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='num_adm_personnel',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='num_computers_desired',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='pop_within_1km',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='pop_within_2km',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='pop_within_3km',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='schools_within_1km',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='schools_within_2km',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='schools_within_3km',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
