# Generated by Django 2.2.28 on 2024-01-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('connection_statistics', '0045_added_school_master_new_fields_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='source',
            field=models.CharField(choices=[('DAILY_CHECK_APP_MLAB', 'Daily Check App/MLab'), ('UNKNOWN', 'Unknown')],
                                   default='UNKNOWN', max_length=50),
        ),
    ]
