# Generated by Django 2.2.28 on 2024-01-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0046_added_source_name_to_realtime_connectivity_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimeconnectivity',
            name='source',
            field=models.CharField(choices=[('DAILY_CHECK_APP_MLAB', 'Daily Check App/MLab'), ('QOS', 'QoS'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50),
        ),
    ]
