# Generated by Django 2.2.28 on 2024-02-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0017_added_description_ui_lebel_field'),
        ('connection_statistics', '0047_added_qos_source_name_to_realtime_connectivity_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtimeconnectivity',
            name='source',
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='connectivity_upload_speed',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='live_data_source',
            field=models.CharField(choices=[('DAILY_CHECK_APP_MLAB', 'Daily Check App/MLab'), ('QOS', 'QoS'), ('DAILY_CHECK_APP_MLAB_QOS', 'Daily Check APP/MLab/QoS'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='connectivity_upload_speed',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='live_data_source',
            field=models.CharField(choices=[('DAILY_CHECK_APP_MLAB', 'Daily Check App/MLab'), ('QOS', 'QoS'), ('DAILY_CHECK_APP_MLAB_QOS', 'Daily Check APP/MLab/QoS'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='connectivity_upload_speed',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='live_data_source',
            field=models.CharField(choices=[('DAILY_CHECK_APP_MLAB', 'Daily Check App/MLab'), ('QOS', 'QoS'), ('DAILY_CHECK_APP_MLAB_QOS', 'Daily Check APP/MLab/QoS'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='connectivity_upload_speed',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='live_data_source',
            field=models.CharField(choices=[('DAILY_CHECK_APP_MLAB', 'Daily Check App/MLab'), ('QOS', 'QoS'), ('DAILY_CHECK_APP_MLAB_QOS', 'Daily Check APP/MLab/QoS'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='connectivity_upload_speed',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='live_data_source',
            field=models.CharField(choices=[('DAILY_CHECK_APP_MLAB', 'Daily Check App/MLab'), ('QOS', 'QoS'), ('DAILY_CHECK_APP_MLAB_QOS', 'Daily Check APP/MLab/QoS'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='countrydailystatus',
            unique_together={('date', 'country', 'live_data_source')},
        ),
        migrations.AlterUniqueTogether(
            name='schooldailystatus',
            unique_together={('date', 'school', 'live_data_source')},
        ),
    ]
