# Generated by Django 2.2.28 on 2024-03-11 13:30

from django.db import migrations
import proco.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0048_added_live_data_source_and_upload_speed_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydailystatus',
            name='deleted',
            field=proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='deleted',
            field=proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='deleted',
            field=proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='deleted',
            field=proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='deleted',
            field=proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
