# Generated by Django 2.2.28 on 2024-03-13 07:57

from django.db import migrations, models
import proco.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0049_added_soft_deletion_to_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='connectivity_govt_collection_year',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='connectivity_govt_ingestion_timestamp',
            field=proco.core.models.CustomDateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='disputed_region',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='nearest_nr_distance',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='school_data_collection_modality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='school_data_collection_year',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='school_data_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='school_location_ingestion_timestamp',
            field=proco.core.models.CustomDateTimeField(blank=True, null=True),
        ),
    ]
