# Generated by Django 2.2.28 on 2024-03-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0028_added_soft_deletion_to_model'),
        ('locations', '0018_added_soft_deletion_to_model'),
        ('connection_statistics', '0050_added_school_master_data_source_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countrydailystatus',
            unique_together={('date', 'country', 'live_data_source', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='countryweeklystatus',
            unique_together={('year', 'week', 'country', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='schooldailystatus',
            unique_together={('date', 'school', 'live_data_source', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolweeklystatus',
            unique_together={('year', 'week', 'school', 'deleted')},
        ),
    ]
