# Generated by Django 2.2.28 on 2024-04-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0051_updated_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydailystatus',
            name='jitter_download',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='jitter_upload',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='roundtrip_time',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='rtt_packet_loss_pct',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='percentage', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='jitter_download',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='jitter_upload',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='roundtrip_time',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='rtt_packet_loss_pct',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='percentage', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='jitter_download',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='jitter_upload',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='roundtrip_time',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='rtt_packet_loss_pct',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='percentage', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='jitter_download',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='jitter_upload',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='roundtrip_time',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='rtt_packet_loss_pct',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='percentage', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='jitter_download',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='jitter_upload',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='roundtrip_time',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='rtt_packet_loss_pct',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='percentage', null=True),
        ),
    ]
