# Generated by Django 2.2.28 on 2024-04-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0052_added_new_qos_fields_for_live_layers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydailystatus',
            name='connectivity_latency',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='connectivity_latency',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AlterField(
            model_name='realtimeconnectivity',
            name='connectivity_latency',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AlterField(
            model_name='schooldailystatus',
            name='connectivity_latency',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity_latency',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
    ]
