# Generated by Django 2.2.28 on 2024-04-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0056_jitter_upload_field_conversion_from_int_to_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydailystatus',
            name='rtt_packet_loss_pct',
            field=models.FloatField(blank=True, default=None, help_text='percentage', null=True),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='rtt_packet_loss_pct',
            field=models.FloatField(blank=True, default=None, help_text='percentage', null=True),
        ),
        migrations.AlterField(
            model_name='realtimeconnectivity',
            name='rtt_packet_loss_pct',
            field=models.FloatField(blank=True, default=None, help_text='percentage', null=True),
        ),
        migrations.AlterField(
            model_name='schooldailystatus',
            name='rtt_packet_loss_pct',
            field=models.FloatField(blank=True, default=None, help_text='percentage', null=True),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='rtt_packet_loss_pct',
            field=models.FloatField(blank=True, default=None, help_text='percentage', null=True),
        ),
    ]
