# Generated by Django 2.2.28 on 2024-05-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0057_rtt_packet_loss_pct_field_conversion_from_int_to_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydailystatus',
            name='connectivity_latency_probe',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='connectivity_speed_probe',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='connectivity_upload_speed_probe',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='connectivity_latency_probe',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='connectivity_speed_probe',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='connectivity_upload_speed_probe',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='connectivity_latency_probe',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='connectivity_speed_probe',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='connectivity_upload_speed_probe',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='connectivity_latency_probe',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='connectivity_speed_probe',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='connectivity_upload_speed_probe',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='connectivity_latency_probe',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='connectivity_speed_probe',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='connectivity_upload_speed_probe',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
    ]
