# Generated by Django 2.2.28 on 2024-05-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('connection_statistics', '0058_added_qos_kenya_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countrydailystatus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='countryweeklystatus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='schooldailystatus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='schoolweeklystatus',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='countrydailystatus',
            constraint=models.UniqueConstraint(fields=('date', 'country', 'live_data_source', 'deleted'),
                                               name='countrydailystatus_unique_with_deleted'),
        ),
        migrations.AddConstraint(
            model_name='countrydailystatus',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None),
                                               fields=('date', 'country', 'live_data_source'),
                                               name='countrydailystatus_unique_without_deleted'),
        ),
        migrations.AddConstraint(
            model_name='countryweeklystatus',
            constraint=models.UniqueConstraint(fields=('year', 'week', 'country', 'deleted'),
                                               name='countryweeklystatus_unique_with_deleted'),
        ),
        migrations.AddConstraint(
            model_name='countryweeklystatus',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('year', 'week', 'country'),
                                               name='countryweeklystatus_unique_without_deleted'),
        ),
        migrations.AddConstraint(
            model_name='schooldailystatus',
            constraint=models.UniqueConstraint(fields=('date', 'school', 'live_data_source', 'deleted'),
                                               name='schooldailystatus_unique_with_deleted'),
        ),
        migrations.AddConstraint(
            model_name='schooldailystatus',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None),
                                               fields=('date', 'school', 'live_data_source'),
                                               name='schooldailystatus_unique_without_deleted'),
        ),
        migrations.AddConstraint(
            model_name='schoolweeklystatus',
            constraint=models.UniqueConstraint(fields=('year', 'week', 'school', 'deleted'),
                                               name='schoolweeklystatus_unique_with_deleted'),
        ),
        migrations.AddConstraint(
            model_name='schoolweeklystatus',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('year', 'week', 'school'),
                                               name='schoolweeklystatus_unique_without_deleted'),
        ),
    ]
