# Generated by Django 2.2.28 on 2024-05-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0059_added_valid_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='num_computers',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
