# Generated by Django 2.2.28 on 2024-05-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0061_updated_max_allowed_values_for_school_weekly_computer_desired_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='num_students',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
