# Generated by Django 2.2.28 on 2024-06-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('connection_statistics', '0062_updated_max_allowed_values_num_students_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='coverage_type',
            field=models.CharField(
                choices=[('unknown', 'Unknown'), ('no', 'No'), ('2g', '2G'), ('3g', '3G'), ('4g', '4G'), ('5g', '5G')],
                default='unknown', max_length=8),
        ),
    ]
