# Generated by Django 2.2.28 on 2024-08-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0063_added_5g_choice_in_coverage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydailystatus',
            name='connectivity_speed_mean',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='connectivity_upload_speed_mean',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='connectivity_speed_mean',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='connectivity_upload_speed_mean',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='connectivity_speed_mean',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='connectivity_upload_speed_mean',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='connectivity_speed_mean',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='connectivity_upload_speed_mean',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='connectivity_speed_mean',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='connectivity_upload_speed_mean',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
    ]
