# Generated by Django 2.2.28 on 2025-01-16 12:48

from django.db import migrations
import proco.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0067_added_new_school_master_fields_for_honduras_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydailystatus',
            name='connectivity_speed',
            field=proco.core.models.PositiveBigIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='connectivity_speed',
            field=proco.core.models.PositiveBigIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AlterField(
            model_name='realtimeconnectivity',
            name='connectivity_speed',
            field=proco.core.models.PositiveBigIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AlterField(
            model_name='schooldailystatus',
            name='connectivity_speed',
            field=proco.core.models.PositiveBigIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity_speed',
            field=proco.core.models.PositiveBigIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
    ]
