# Generated by Django 2.2.28 on 2025-01-16 12:48

from django.db import migrations
import proco.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0068_increased_download_field_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydailystatus',
            name='connectivity_upload_speed',
            field=proco.core.models.PositiveBigIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='connectivity_upload_speed',
            field=proco.core.models.PositiveBigIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AlterField(
            model_name='realtimeconnectivity',
            name='connectivity_upload_speed',
            field=proco.core.models.PositiveBigIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AlterField(
            model_name='schooldailystatus',
            name='connectivity_upload_speed',
            field=proco.core.models.PositiveBigIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity_upload_speed',
            field=proco.core.models.PositiveBigIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
    ]
