# Generated by Django 2.2.28 on 2026-02-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0069_increased_upload_field_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydailystatus',
            name='uptime',
            field=models.FloatField(blank=True, default=None, help_text='percentage', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='uptime',
            field=models.FloatField(blank=True, default=None, help_text='percentage', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='uptime',
            field=models.FloatField(blank=True, default=None, help_text='percentage', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='uptime',
            field=models.FloatField(blank=True, default=None, help_text='percentage', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='uptime',
            field=models.FloatField(blank=True, default=None, help_text='percentage', null=True),
        ),
    ]
