# Generated by Django 2.2.28 on 2025-05-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0069_increased_upload_field_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydailystatus',
            name='inbound_traffic_sum',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='is_connected_all',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='is_connected_true',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='latency_max',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='latency_mean',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='latency_min',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='outbound_traffic_sum',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='pe_egress',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='pe_ingress',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='signal_max',
            field=models.FloatField(blank=True, default=None, help_text='dBM', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='signal_mean',
            field=models.FloatField(blank=True, default=None, help_text='dBM', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='speed_download_max',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='speed_upload_max',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='inbound_traffic_sum',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='is_connected_all',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='is_connected_true',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='latency_max',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='latency_mean',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='latency_min',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='outbound_traffic_sum',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='pe_egress',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='pe_ingress',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='signal_max',
            field=models.FloatField(blank=True, default=None, help_text='dBM', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='signal_mean',
            field=models.FloatField(blank=True, default=None, help_text='dBM', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='speed_download_max',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='speed_upload_max',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='inbound_traffic_sum',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='is_connected_all',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='is_connected_true',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='latency_max',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='latency_mean',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='latency_min',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='outbound_traffic_sum',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='pe_egress',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='pe_ingress',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='signal_max',
            field=models.FloatField(blank=True, default=None, help_text='dBM', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='signal_mean',
            field=models.FloatField(blank=True, default=None, help_text='dBM', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='speed_download_max',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='speed_upload_max',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='inbound_traffic_sum',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='is_connected_all',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='is_connected_true',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='latency_max',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='latency_mean',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='latency_min',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='outbound_traffic_sum',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='pe_egress',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='pe_ingress',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='signal_max',
            field=models.FloatField(blank=True, default=None, help_text='dBM', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='signal_mean',
            field=models.FloatField(blank=True, default=None, help_text='dBM', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='speed_download_max',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='speed_upload_max',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='inbound_traffic_sum',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='is_connected_all',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='is_connected_true',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='latency_max',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='latency_mean',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='latency_min',
            field=models.FloatField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='outbound_traffic_sum',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='pe_egress',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='pe_ingress',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='signal_max',
            field=models.FloatField(blank=True, default=None, help_text='dBM', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='signal_mean',
            field=models.FloatField(blank=True, default=None, help_text='dBM', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='speed_download_max',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='speed_upload_max',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
    ]
