# Generated by Django 2.2.28 on 2026-03-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0070_auto_20260224_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydailystatus',
            name='is_connected_all',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Is Connected All', null=True),
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='is_connected_true',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Is Connected', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='is_connected_all',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Is Connected All', null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='is_connected_true',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Is Connected', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='is_connected_all',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Is Connected All', null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='is_connected_true',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Is Connected', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='is_connected_all',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Is Connected All', null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='is_connected_true',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Is Connected', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='is_connected_all',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Is Connected All', null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='is_connected_true',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Is Connected', null=True),
        ),
    ]
