# Generated by Django 2.2.28 on 2026-07-18 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0034_school_is_verified_school'),
        ('locations', '0022_added_disclaimer_field_on_country'),
        ('connection_statistics', '0070_auto_20260403_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolWeeklyRollup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('year', models.PositiveSmallIntegerField()),
                ('week', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('live_data_source', models.CharField(default='UNKNOWN', max_length=50)),
                ('connectivity_speed_sum', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_speed_count', models.PositiveIntegerField(default=0)),
                ('connectivity_speed_min', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_speed_max', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_upload_speed_sum', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_upload_speed_count', models.PositiveIntegerField(default=0)),
                ('connectivity_upload_speed_min', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_upload_speed_max', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_latency_sum', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_latency_count', models.PositiveIntegerField(default=0)),
                ('connectivity_latency_min', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_latency_max', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_speed_probe_sum', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_speed_probe_count', models.PositiveIntegerField(default=0)),
                ('connectivity_speed_probe_min', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_speed_probe_max', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_upload_speed_probe_sum', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_upload_speed_probe_count', models.PositiveIntegerField(default=0)),
                ('connectivity_upload_speed_probe_min', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_upload_speed_probe_max', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_latency_probe_sum', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_latency_probe_count', models.PositiveIntegerField(default=0)),
                ('connectivity_latency_probe_min', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_latency_probe_max', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_speed_mean_sum', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_speed_mean_count', models.PositiveIntegerField(default=0)),
                ('connectivity_speed_mean_min', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_speed_mean_max', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_upload_speed_mean_sum', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_upload_speed_mean_count', models.PositiveIntegerField(default=0)),
                ('connectivity_upload_speed_mean_min', models.FloatField(blank=True, default=None, null=True)),
                ('connectivity_upload_speed_mean_max', models.FloatField(blank=True, default=None, null=True)),
                ('roundtrip_time_sum', models.FloatField(blank=True, default=None, null=True)),
                ('roundtrip_time_count', models.PositiveIntegerField(default=0)),
                ('roundtrip_time_min', models.FloatField(blank=True, default=None, null=True)),
                ('roundtrip_time_max', models.FloatField(blank=True, default=None, null=True)),
                ('jitter_download_sum', models.FloatField(blank=True, default=None, null=True)),
                ('jitter_download_count', models.PositiveIntegerField(default=0)),
                ('jitter_download_min', models.FloatField(blank=True, default=None, null=True)),
                ('jitter_download_max', models.FloatField(blank=True, default=None, null=True)),
                ('jitter_upload_sum', models.FloatField(blank=True, default=None, null=True)),
                ('jitter_upload_count', models.PositiveIntegerField(default=0)),
                ('jitter_upload_min', models.FloatField(blank=True, default=None, null=True)),
                ('jitter_upload_max', models.FloatField(blank=True, default=None, null=True)),
                ('rtt_packet_loss_pct_sum', models.FloatField(blank=True, default=None, null=True)),
                ('rtt_packet_loss_pct_count', models.PositiveIntegerField(default=0)),
                ('rtt_packet_loss_pct_min', models.FloatField(blank=True, default=None, null=True)),
                ('rtt_packet_loss_pct_max', models.FloatField(blank=True, default=None, null=True)),
                ('uptime_sum', models.FloatField(blank=True, default=None, null=True)),
                ('uptime_count', models.PositiveIntegerField(default=0)),
                ('uptime_min', models.FloatField(blank=True, default=None, null=True)),
                ('uptime_max', models.FloatField(blank=True, default=None, null=True)),
                ('is_connected_true_sum', models.FloatField(blank=True, default=None, null=True)),
                ('is_connected_true_count', models.PositiveIntegerField(default=0)),
                ('is_connected_true_min', models.FloatField(blank=True, default=None, null=True)),
                ('is_connected_true_max', models.FloatField(blank=True, default=None, null=True)),
                ('is_connected_all_sum', models.FloatField(blank=True, default=None, null=True)),
                ('is_connected_all_count', models.PositiveIntegerField(default=0)),
                ('is_connected_all_min', models.FloatField(blank=True, default=None, null=True)),
                ('is_connected_all_max', models.FloatField(blank=True, default=None, null=True)),
                ('admin1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_weekly_rollup', to='locations.CountryAdminMetadata')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_weekly_rollup', to='locations.Country')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_rollup', to='schools.School')),
            ],
            options={
                'verbose_name': 'School Weekly Rollup',
                'verbose_name_plural': 'School Weekly Rollup',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='schoolweeklyrollup',
            index=models.Index(fields=['country', 'live_data_source', 'date'], name='swr_country_source_date_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolweeklyrollup',
            index=models.Index(fields=['admin1', 'live_data_source', 'date'], name='swr_admin1_source_date_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolweeklyrollup',
            index=models.Index(fields=['school', 'live_data_source', 'date'], name='swr_school_source_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolweeklyrollup',
            constraint=models.UniqueConstraint(fields=('school', 'year', 'week', 'live_data_source'), name='schoolweeklyrollup_unique'),
        ),
    ]
