# Generated by Django 2.2.28 on 2025-07-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0070_added_kenya_qos_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydailystatus',
            name='inbound_traffic_sum',
            field=models.BigIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AlterField(
            model_name='countrydailystatus',
            name='outbound_traffic_sum',
            field=models.BigIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='inbound_traffic_sum',
            field=models.BigIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='outbound_traffic_sum',
            field=models.BigIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AlterField(
            model_name='realtimeconnectivity',
            name='inbound_traffic_sum',
            field=models.BigIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AlterField(
            model_name='realtimeconnectivity',
            name='outbound_traffic_sum',
            field=models.BigIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AlterField(
            model_name='schooldailystatus',
            name='inbound_traffic_sum',
            field=models.BigIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AlterField(
            model_name='schooldailystatus',
            name='outbound_traffic_sum',
            field=models.BigIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='inbound_traffic_sum',
            field=models.BigIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='outbound_traffic_sum',
            field=models.BigIntegerField(blank=True, default=None, help_text='byte', null=True),
        ),
    ]
