# Generated by Django 2.2.28 on 2026-04-07 11:50

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import proco.core.models
import proco.utils.dates


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0070_auto_20260403_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityDailyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('connectivity_speed', proco.core.models.PositiveBigIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('connectivity_upload_speed', proco.core.models.PositiveBigIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('connectivity_latency', models.FloatField(blank=True, default=None, help_text='ms', null=True)),
                ('connectivity_speed_probe', models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('connectivity_upload_speed_probe', models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('connectivity_latency_probe', models.FloatField(blank=True, default=None, help_text='ms', null=True)),
                ('connectivity_speed_mean', models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('connectivity_upload_speed_mean', models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('roundtrip_time', models.FloatField(blank=True, default=None, help_text='ms', null=True)),
                ('jitter_download', models.FloatField(blank=True, default=None, help_text='ms', null=True)),
                ('jitter_upload', models.FloatField(blank=True, default=None, help_text='ms', null=True)),
                ('rtt_packet_loss_pct', models.FloatField(blank=True, default=None, help_text='percentage', null=True)),
                ('uptime', models.FloatField(blank=True, default=None, help_text='percentage', null=True)),
                ('is_connected_true', models.FloatField(blank=True, default=None, help_text='Is Connected', null=True)),
                ('is_connected_all', models.FloatField(blank=True, default=None, help_text='Is Connected All', null=True)),
                ('live_data_source', models.CharField(choices=[('DAILY_CHECK_APP_MLAB', 'Daily Check App/MLab'), ('QOS', 'QoS'), ('DAILY_CHECK_APP_MLAB_QOS', 'Daily Check APP/MLab/QoS'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Daily Connectivity Summary',
                'verbose_name_plural': 'Daily Connectivity Summary',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EntityRealTimeConnectivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('connectivity_speed', proco.core.models.PositiveBigIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('connectivity_upload_speed', proco.core.models.PositiveBigIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('connectivity_latency', models.FloatField(blank=True, default=None, help_text='ms', null=True)),
                ('connectivity_speed_probe', models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('connectivity_upload_speed_probe', models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('connectivity_latency_probe', models.FloatField(blank=True, default=None, help_text='ms', null=True)),
                ('connectivity_speed_mean', models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('connectivity_upload_speed_mean', models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('roundtrip_time', models.FloatField(blank=True, default=None, help_text='ms', null=True)),
                ('jitter_download', models.FloatField(blank=True, default=None, help_text='ms', null=True)),
                ('jitter_upload', models.FloatField(blank=True, default=None, help_text='ms', null=True)),
                ('rtt_packet_loss_pct', models.FloatField(blank=True, default=None, help_text='percentage', null=True)),
                ('uptime', models.FloatField(blank=True, default=None, help_text='percentage', null=True)),
                ('is_connected_true', models.FloatField(blank=True, default=None, help_text='Is Connected', null=True)),
                ('is_connected_all', models.FloatField(blank=True, default=None, help_text='Is Connected All', null=True)),
                ('live_data_source', models.CharField(choices=[('DAILY_CHECK_APP_MLAB', 'Daily Check App/MLab'), ('QOS', 'QoS'), ('DAILY_CHECK_APP_MLAB_QOS', 'Daily Check APP/MLab/QoS'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Real Time Connectivity Data',
                'verbose_name_plural': 'Real Time Connectivity Data',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EntityRealTimeRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('rt_registered', models.BooleanField(default=False)),
                ('rt_registration_date', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('rt_source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Real Time Registration Status',
                'verbose_name_plural': 'Real Time Registration Data',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EntityWeeklyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('connectivity_speed', proco.core.models.PositiveBigIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('connectivity_upload_speed', proco.core.models.PositiveBigIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('connectivity_latency', models.FloatField(blank=True, default=None, help_text='ms', null=True)),
                ('connectivity_speed_probe', models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('connectivity_upload_speed_probe', models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('connectivity_latency_probe', models.FloatField(blank=True, default=None, help_text='ms', null=True)),
                ('connectivity_speed_mean', models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('connectivity_upload_speed_mean', models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True)),
                ('roundtrip_time', models.FloatField(blank=True, default=None, help_text='ms', null=True)),
                ('jitter_download', models.FloatField(blank=True, default=None, help_text='ms', null=True)),
                ('jitter_upload', models.FloatField(blank=True, default=None, help_text='ms', null=True)),
                ('rtt_packet_loss_pct', models.FloatField(blank=True, default=None, help_text='percentage', null=True)),
                ('uptime', models.FloatField(blank=True, default=None, help_text='percentage', null=True)),
                ('is_connected_true', models.FloatField(blank=True, default=None, help_text='Is Connected', null=True)),
                ('is_connected_all', models.FloatField(blank=True, default=None, help_text='Is Connected All', null=True)),
                ('live_data_source', models.CharField(choices=[('DAILY_CHECK_APP_MLAB', 'Daily Check App/MLab'), ('QOS', 'QoS'), ('DAILY_CHECK_APP_MLAB_QOS', 'Daily Check APP/MLab/QoS'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('year', models.PositiveSmallIntegerField(default=proco.utils.dates.get_current_year)),
                ('week', models.PositiveSmallIntegerField(default=proco.utils.dates.get_current_week)),
                ('date', models.DateField()),
                ('download_speed_benchmark', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Weekly Summary',
                'verbose_name_plural': 'Weekly Summary',
                'ordering': ('id',),
            },
        ),
    ]
