# Generated by Django 2.2.28 on 2026-02-13 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0070_entitydailystatus_entityrealtimeconnectivity_entityrealtimeregistration_entityweeklystatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityweeklystatus',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_status', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='entityrealtimeregistration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_entityrealtimeregistrations', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='entityrealtimeregistration',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_registration_status', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='entityrealtimeregistration',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_entityrealtimeregistrations', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AddField(
            model_name='entityrealtimeconnectivity',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_status', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='entitydailystatus',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_status', to='entities.Entity'),
        ),
        migrations.AddConstraint(
            model_name='entityweeklystatus',
            constraint=models.UniqueConstraint(fields=('year', 'week', 'entity', 'deleted'), name='entityweeklystatus_unique_with_deleted'),
        ),
        migrations.AddConstraint(
            model_name='entityweeklystatus',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('year', 'week', 'entity'), name='entityweeklystatus_unique_without_deleted'),
        ),
        migrations.AddConstraint(
            model_name='entitydailystatus',
            constraint=models.UniqueConstraint(fields=('date', 'entity', 'live_data_source', 'deleted'), name='entitydailystatus_unique_with_deleted'),
        ),
        migrations.AddConstraint(
            model_name='entitydailystatus',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('date', 'entity', 'live_data_source'), name='entitydailystatus_unique_without_deleted'),
        ),
    ]
