# Generated by Django 2.2.28 on 2026-08-01 18:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import proco.utils.dates


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0034_school_is_verified_school'),
        ('locations', '0022_added_disclaimer_field_on_country'),
        ('connection_statistics', '0071_add_sds_school_date_source_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRealTimeWeeklyMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('year', models.PositiveSmallIntegerField(default=proco.utils.dates.get_current_year)),
                ('week', models.PositiveSmallIntegerField(default=proco.utils.dates.get_current_week)),
                ('date', models.DateField()),
                ('config_hash', models.CharField(db_index=True, max_length=64)),
                ('live_data_sources', models.CharField(max_length=255)),
                ('metric_name', models.CharField(max_length=64)),
                ('agg_function', models.CharField(choices=[('avg', 'Average'), ('min', 'Minimum'), ('max', 'Maximum'), ('sum', 'Sum'), ('median|50', 'Median 50'), ('median|90', 'Median 90')], max_length=32)),
                ('agg_value', models.FloatField(blank=True, default=None, null=True)),
                ('sample_count', models.PositiveIntegerField(blank=True, default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_realtime_weekly_metrics', to='locations.Country')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_weekly_metrics', to='schools.School')),
            ],
            options={
                'verbose_name': 'School Real Time Weekly Metric',
                'verbose_name_plural': 'School Real Time Weekly Metrics',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='schoolrealtimeweeklymetric',
            index=models.Index(fields=['school', 'year', 'week', 'config_hash'], name='srtwm_school_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolrealtimeweeklymetric',
            index=models.Index(fields=['country', 'year', 'week', 'config_hash'], name='srtwm_country_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolrealtimeweeklymetric',
            index=models.Index(fields=['config_hash', 'year', 'week'], name='srtwm_hash_week_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolrealtimeweeklymetric',
            index=models.Index(fields=['date'], name='srtwm_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolrealtimeweeklymetric',
            constraint=models.UniqueConstraint(fields=('school', 'year', 'week', 'config_hash'), name='schoolrealtimeweeklymetric_unique'),
        ),
    ]
