# Generated by Django 2.2.28 on 2026-07-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0072_auto_20260407_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityrealtimeconnectivity',
            name='version',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
