# Generated by Django 2.2.28 on 2026-03-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0072_auto_20260109_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydailystatus',
            name='is_connected_all',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='countrydailystatus',
            name='is_connected_true',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='is_connected_all',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='is_connected_true',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='realtimeconnectivity',
            name='is_connected_all',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='realtimeconnectivity',
            name='is_connected_true',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schooldailystatus',
            name='is_connected_all',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schooldailystatus',
            name='is_connected_true',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='is_connected_all',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='is_connected_true',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
