# Generated by Django 2.2.16 on 2020-10-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0029_auto_20201020_1143'),
        ('schools', '0010_auto_20201013_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='last_weekly_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_school', to='connection_statistics.SchoolWeeklyStatus'),
        ),
    ]
