# Generated by Django 2.2.16 on 2020-11-03 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schools', '0015_school_name_lower'),
    ]

    operations = []
