# Generated by Django 2.2.15 on 2020-11-12 14:48


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_auto_20201103_1415'),
    ]

    operations = []
