# Generated by Django 2.2.19 on 2023-08-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_auto_20210415_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='connectivity_status',
            field=models.CharField(blank=True, default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='coverage_type',
            field=models.CharField(blank=True, default='unknown', max_length=10),
        ),
        # migrations.AddField(
        #    model_name='school',
        #    name='education_level_regional',
        #    field=models.CharField(blank=True, max_length=6400007),
        # ),
        # migrations.AddField(
        #    model_name='school',
        #    name='giga_id_school',
        #    field=models.CharField(blank=True, max_length=50),
        # ),
        # migrations.AlterField(
        #     model_name='school',
        #     name='education_level',
        #     field=models.CharField(blank=True, max_length=255),
        # ),
    ]
