# Generated by Django 2.2.19 on 2023-10-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_auto_20230816_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='coverage_status',
            field=models.CharField(blank=True, default='unknown', max_length=10),
        ),
    ]
