# Generated by Django 2.2.28 on 2024-01-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_school_coverage_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='establishment_year',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
