# Generated by Django 2.2.28 on 2024-02-02 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0015_added_country_admin_model'),
        ('schools', '0024_added_school_master_new_fields_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admin1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin1_schools', to='locations.CountryAdminMetadata'),
        ),
        migrations.AddField(
            model_name='school',
            name='admin2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin2_schools', to='locations.CountryAdminMetadata'),
        ),
    ]
