# Generated by Django 2.2.28 on 2024-02-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0025_added_admin_id_fields_to_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='admin_1_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='admin_2_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='admin_3_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='admin_4_name',
        ),
    ]
