# Generated by Django 2.2.28 on 2024-03-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0026_removed_admin_free_text_fileds_from_school_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='education_level',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(default='Name unknown', max_length=1000),
        ),
        migrations.AlterField(
            model_name='school',
            name='name_lower',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=1000),
        ),
    ]
