# Generated by Django 2.2.28 on 2024-05-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0028_added_soft_deletion_to_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='giga_id_school',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
