# Generated by Django 2.2.28 on 2024-06-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schools', '0029_added_indexes_on_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('country', 'giga_id_school', 'deleted'),
                                               name='schools_giga_id_unique_with_deleted'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('country', 'giga_id_school'),
                                               name='schools_giga_id_unique_without_deleted'),
        ),
    ]
