# Generated by Django 2.2.28 on 2024-11-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0030_added_unique_constraint_on_country_and_giga_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='education_level_lower',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type_lower',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
    ]
