# Generated by Django 2.2.28 on 2024-12-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0031_added_lower_case_fields_for_filter_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='location',
        ),
    ]
