# Generated by Django 2.2.28 on 2024-12-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0032_added_school_education_level_govt_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='location',
        ),
    ]
