# Generated by Django 2.2.28 on 2025-03-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0032_removed_location_id_field_from_school_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='education_level_govt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='education_level_govt_lower',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
    ]
