# Generated by Django 2.2.28 on 2026-06-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0033_removed_location_id_field_from_school_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_verified_school',
            field=models.BooleanField(default=True),
        ),
    ]
