# Generated by Django 2.2.28 on 2025-05-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0034_added_school_master_status_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='establishment_year',
        ),
        migrations.AddField(
            model_name='school',
            name='last_master_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='_school', to='schools.SchoolMasterStatus'),
        ),
    ]
