# Generated by Django 2.2.16 on 2020-09-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20200915_0723'),
        ('connection_statistics', '0018_countryweeklystatus_schools_with_data_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='date_of_join',
            field=models.DateField(null=True),
        ),
    ]
