# Generated by Django 2.2.15 on 2020-10-22 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0029_auto_20201020_1143'),
        ('locations', '0008_auto_20201019_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='last_weekly_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_country', to='connection_statistics.CountryWeeklyStatus'),
        ),
    ]
