# Generated by Django 2.2.28 on 2023-12-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_master_data_migrations_country_benchmark_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso3_format',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
