# Generated by Django 2.2.19 on 2024-01-05 05:37

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_school_master_data_source_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='benchmark_metadata',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
    ]
