# Generated by Django 2.2.28 on 2024-01-23 12:09

import django.db.models.deletion
import jsonfield.fields
from django.conf import settings
from django.db import migrations, models

import proco.core.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0014_country_meta_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryAdminMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at',
                 proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('centroid', jsonfield.fields.JSONField(blank=True, default=list, null=True)),
                ('bbox', jsonfield.fields.JSONField(blank=True, default=list, null=True)),
                ('layer_name', models.CharField(choices=[('adm0', 'Admin 0'), ('adm1', 'Admin 1'), ('adm2', 'Admin 2')],
                                                default='adm1', max_length=10, verbose_name='Layer Name')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('giga_id_admin', models.CharField(blank=True, max_length=50, null=True)),
                ('mapbox_id', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='country_admins', to='locations.Country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                 related_name='created_countryadminmetadatas',
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                   related_name='updated_countryadminmetadatas', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Last Updated By')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='children', to='locations.CountryAdminMetadata')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
