# Generated by Django 2.2.28 on 2024-02-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0016_removed_benchmark_columns_from_country_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryadminmetadata',
            name='description_ui_label',
            field=models.CharField(default='Admins', max_length=255),
        ),
    ]
