# Generated by Django 2.2.28 on 2024-03-11 13:08

from django.db import migrations
import proco.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0017_added_description_ui_lebel_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='deleted',
            field=proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
