# Generated by Django 2.2.28 on 2024-05-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0018_added_soft_deletion_to_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='data_source_description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
