# Generated by Django 2.2.28 on 2024-12-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_added_country_data_source_description_field'),
        ('schools', '0033_removed_location_id_field_from_school_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
