# Generated by Django 2.2.28 on 2024-12-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0020_deleted_location_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='geometry_simplified',
        ),
    ]
