# Generated by Django 2.2.28 on 2025-06-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0021_removed_geometry_simplified_field_from_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_disclaimer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
