FROM postgis/postgis:15-3.3

RUN apt-get update && apt-get install -y --no-install-recommends bzip2 && rm -rf /var/lib/apt/lists/*

ADD ./docker/initdb-local.sh /docker-entrypoint-initdb.d/initdb-proco.sh
RUN chmod +x /docker-entrypoint-initdb.d/initdb-proco.sh