# Generated by Django 2.2.28 on 2025-12-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giga_meter', '0001_giga_meter_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigaMeter_ConnectivityPingChecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('is_connected', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('giga_id_school', models.TextField()),
                ('app_local_uuid', models.TextField()),
                ('browser_id', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('latency', models.FloatField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'connectivity_ping_checks',
                'managed': False,
            },
        ),
    ]
