# Generated by Django 2.2.28 on 2026-01-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giga_meter', '0001_giga_meter_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectivityPingChecksDailyAggr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_date', models.DateTimeField()),
                ('giga_id_school', models.CharField(db_index=True, max_length=50)),
                ('browser_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_connected_true', models.IntegerField()),
                ('is_connected_all', models.IntegerField()),
                ('uptime', models.FloatField()),
                ('unloaded_latency_avg', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'connectivity_ping_checks_daily_aggr',
                'managed': False,
            },
        ),
    ]
