# Generated by Django 2.2.28 on 2024-02-15 09:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import proco.locations.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('text', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('cta', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=proco.locations.utils.get_random_name_image)),
            ],
        ),
    ]
