# Generated by Django 2.2.28 on 2024-03-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_remove_aboutus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
