# Generated by Django 2.2.28 on 2024-03-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_aboutus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='style',
            field=models.TextField(blank=True, null=True),
        ),
    ]
