# Generated by Django 2.2.28 on 2026-08-13 21:02

import django.core.validators
from django.db import migrations, models
import proco.locations.utils


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_aboutus_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=proco.locations.utils.get_random_name_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'mp4', 'webm'])]),
        ),
    ]
