# Generated by Django 2.2.28 on 2026-08-17 12:49

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import proco.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connection_statistics', '0072_entitydailystatus_entityrealtimeconnectivity_entityrealtimeregistration_entityweeklystatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0023_added_health_data_source_field_on_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('giga_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(default='Name unknown', max_length=1000)),
                ('name_lower', models.CharField(blank=True, db_index=True, editable=False, max_length=1000)),
                ('geopoint', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point')),
                ('environment', models.CharField(blank=True, choices=[('rural', 'Rural'), ('urban', 'Urban')], db_index=True, max_length=20, null=True)),
                ('connectivity_status', models.CharField(blank=True, default='unknown', max_length=10)),
                ('coverage_status', models.CharField(blank=True, default='unknown', max_length=10)),
                ('connectivity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('coverage_type', models.CharField(blank=True, default='unknown', max_length=8, null=True)),
                ('water_availability', models.BooleanField(blank=True, default=None, null=True)),
                ('electricity_availability', models.BooleanField(blank=True, default=None, null=True)),
                ('electricity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('pop_within_1km', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('pop_within_2km', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('pop_within_3km', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('pop_within_5km', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('pop_within_10km', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('connectivity_govt', models.BooleanField(blank=True, default=None, null=True)),
                ('connectivity_type_govt', models.CharField(blank=True, max_length=255, null=True)),
                ('connectivity_govt_collection_year', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('data_source', models.CharField(blank=True, max_length=255, null=True)),
                ('data_collection_year', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('data_collection_modality', models.CharField(blank=True, max_length=255, null=True)),
                ('last_master_status_id', proco.core.models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ('admin1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin1_entities', to='locations.CountryAdminMetadata')),
                ('admin2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin2_entities', to='locations.CountryAdminMetadata')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='locations.Country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_entitys', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'db_table': 'entities_entity',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='HealthEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('dhis2_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('hims_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('hfml_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('facility_id_govt', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('facility_type', models.CharField(blank=True, max_length=255, null=True)),
                ('facility_ownership', models.CharField(blank=True, max_length=255, null=True)),
                ('facility_level', models.CharField(blank=True, max_length=20, null=True)),
                ('health_service_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('is_facility_open', models.BooleanField(blank=True, default=None, null=True)),
                ('licensing_status', models.CharField(blank=True, max_length=50, null=True)),
                ('facility_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('establishment_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('num_beds_total', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_beds_icu', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_theatres', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_toilets', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_healthworkers', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('staff_doctors', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('staff_nurses', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('staff_midwives', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('staff_laboratorians', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('staff_pharmacists', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('emergency_services_available', models.BooleanField(blank=True, default=None, null=True)),
                ('services_offered', models.CharField(blank=True, max_length=500, null=True)),
                ('power_backup_system', models.BooleanField(blank=True, default=None, null=True)),
                ('cold_chain_available', models.BooleanField(blank=True, default=None, null=True)),
                ('waste_management_system', models.CharField(blank=True, max_length=50, null=True)),
                ('hmis_system', models.BooleanField(blank=True, default=None, null=True)),
                ('catchment_population', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_outpatients', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_inpatients', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('facility_address', models.CharField(blank=True, max_length=255, null=True)),
                ('fiber_node_distance', models.FloatField(blank=True, default=None, null=True)),
                ('microwave_node_distance', models.FloatField(blank=True, default=None, null=True)),
                ('nearest_lte_distance', models.FloatField(blank=True, default=None, null=True)),
                ('nearest_umts_distance', models.FloatField(blank=True, default=None, null=True)),
                ('nearest_gsm_distance', models.FloatField(blank=True, default=None, null=True)),
                ('nearest_nr_distance', models.FloatField(blank=True, default=None, null=True)),
                ('num_adm_personnel', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('disputed_region', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_healthentitys', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('entity', models.OneToOneField(limit_choices_to={'entity_type__code': 'health'}, on_delete=django.db.models.deletion.CASCADE, related_name='health_entity', to='entities.Entity')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_healthentitys', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'db_table': 'entities_health_entity',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('code', models.CharField(db_index=True, help_text='Unique short code, e.g. "school", "health", "library"', max_length=20, unique=True, verbose_name='Type Code')),
                ('name', models.CharField(help_text='Human-readable name, e.g. "School", "Health Facility"', max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive types are hidden from APIs and UI')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower values appear first in lists')),
                ('detail_model', models.CharField(blank=True, default='', help_text='App label + model name for entity-specific model, e.g. "entities.HealthEntity"', max_length=100)),
                ('detail_related_name', models.CharField(blank=True, default='', help_text='Related name on Entity for the OneToOne detail model, e.g. "health_entity"', max_length=50)),
                ('master_data_model', models.CharField(blank=True, default='', help_text='App label + model name for master data model, e.g. "data_sources.HealthEntityMasterIntermediateData"', max_length=100)),
                ('extra_config', jsonfield.fields.JSONField(blank=True, default=dict, help_text='Additional type-specific configuration as JSON', null=True)),
                ('is_legacy', models.BooleanField(default=False, help_text='If True, this type maps to the legacy School model instead of Entity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_entitytypes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_entitytypes', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Entity Type',
                'verbose_name_plural': 'Entity Types',
                'db_table': 'entities_entity_type',
                'ordering': ('display_order', 'code'),
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='entities.EntityType'),
        ),
        migrations.AddField(
            model_name='entity',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_entitys', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AddField(
            model_name='entity',
            name='last_weekly_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_entity', to='connection_statistics.EntityWeeklyStatus'),
        ),
        migrations.AddConstraint(
            model_name='healthentity',
            constraint=models.UniqueConstraint(fields=('entity', 'deleted'), name='health_entity_unique_with_deleted'),
        ),
        migrations.AddConstraint(
            model_name='healthentity',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('entity',), name='health_entity_unique_without_deleted'),
        ),
        migrations.AddConstraint(
            model_name='entitytype',
            constraint=models.UniqueConstraint(fields=('code', 'deleted'), name='entity_type_code_unique_with_deleted'),
        ),
        migrations.AddConstraint(
            model_name='entitytype',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('code',), name='entity_type_code_unique_without_deleted'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('entity_type', 'country', 'giga_id', 'deleted'), name='entities_giga_id_unique_with_deleted'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('entity_type', 'country', 'giga_id'), name='entities_giga_id_unique_without_deleted'),
        ),
    ]
