# Generated by Django 2.2.28 on 2025-08-28 10:26

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import proco.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connection_statistics', '0072_added_entity_models'),
        ('locations', '0022_added_disclaimer_field_on_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('entity_name', models.CharField(db_index=True, max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('giga_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(default='Name unknown', max_length=1000)),
                ('name_lower', models.CharField(blank=True, db_index=True, editable=False, max_length=1000)),
                ('geopoint', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point')),
                ('environment', models.CharField(blank=True, choices=[('rural', 'Rural'), ('urban', 'Urban')], db_index=True, max_length=20, null=True)),
                ('connectivity_status', models.CharField(blank=True, default='unknown', max_length=10)),
                ('coverage_status', models.CharField(blank=True, default='unknown', max_length=10)),
                ('last_master_status_id', proco.core.models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('admin1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin1_entities', to='locations.CountryAdminMetadata')),
                ('admin2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin2_entities', to='locations.CountryAdminMetadata')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='locations.Country')),
                ('last_weekly_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_entity', to='connection_statistics.EntityWeeklyStatus')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='HealthMasterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', proco.core.models.CustomDateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', proco.core.models.CustomDateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('created', proco.core.models.CustomDateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('establishment_year', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('water_availability', models.NullBooleanField(default=None)),
                ('electricity_availability', models.NullBooleanField(default=None)),
                ('computer_lab', models.NullBooleanField(default=None)),
                ('download_speed_benchmark', models.FloatField(blank=True, default=None, null=True)),
                ('download_speed_contracted', models.FloatField(blank=True, default=None, null=True)),
                ('electricity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('num_adm_personnel', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_computers_desired', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_computers', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('fiber_node_distance', models.FloatField(blank=True, default=None, null=True)),
                ('microwave_node_distance', models.FloatField(blank=True, default=None, null=True)),
                ('pop_within_1km', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('pop_within_2km', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('pop_within_3km', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('connectivity_govt_collection_year', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('connectivity_govt_ingestion_timestamp', proco.core.models.CustomDateTimeField(blank=True, null=True)),
                ('num_tablets', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('num_robotic_equipment', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('sustainable_business_model', models.NullBooleanField(default=None)),
                ('computer_availability', models.NullBooleanField(default=None)),
                ('device_availability', models.NullBooleanField(default=None)),
                ('disputed_region', models.BooleanField(default=False)),
                ('connectivity_govt', models.NullBooleanField(default=None)),
                ('connectivity_type_govt', models.CharField(blank=True, max_length=255, null=True)),
                ('connectivity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('connectivity_type_root', models.CharField(blank=True, max_length=255, null=True)),
                ('nearest_lte_distance', models.FloatField(blank=True, default=None, null=True)),
                ('nearest_umts_distance', models.FloatField(blank=True, default=None, null=True)),
                ('nearest_gsm_distance', models.FloatField(blank=True, default=None, null=True)),
                ('nearest_nr_distance', models.FloatField(blank=True, default=None, null=True)),
                ('data_source', models.CharField(blank=True, max_length=255, null=True)),
                ('data_collection_year', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('data_collection_modality', models.CharField(blank=True, max_length=255, null=True)),
                ('location_ingestion_timestamp', proco.core.models.CustomDateTimeField(blank=True, null=True)),
                ('connectivity', models.NullBooleanField(default=None)),
                ('coverage_type', models.CharField(default='unknown', max_length=8)),
                ('version', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_healthmasterstatuss', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='master_status', to='entities.Entity', verbose_name='Master Sync')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_healthmasterstatuss', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='healthmasterstatus',
            constraint=models.UniqueConstraint(fields=('entity', 'version', 'deleted'), name='entities_master_status_unique_with_deleted'),
        ),
        migrations.AddConstraint(
            model_name='healthmasterstatus',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('entity', 'version'), name='entities_master_status_unique_without_deleted'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('entity_name', 'country', 'giga_id', 'deleted'), name='entities_giga_id_unique_with_deleted'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('entity_name', 'country', 'giga_id'), name='entities_giga_id_unique_without_deleted'),
        ),
    ]
