# Generated by Django 2.2.28 on 2026-04-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
