# Generated by Django 2.2.28 on 2025-11-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_added_entity_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmasterstatus',
            name='connectivity_govt_collection_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthmasterstatus',
            name='download_speed_contracted',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
