# Generated by Django 2.2.28 on 2026-04-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20260423_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthentity',
            name='facility_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthentity',
            name='facility_id_govt',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthentity',
            name='facility_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='healthentity',
            name='licensing_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
