# Generated by Django 2.2.28 on 2026-07-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20260423_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='connectivity_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='coverage_type',
            field=models.CharField(blank=True, default='unknown', max_length=8, null=True),
        ),
    ]
