# Generated by Django 2.2.28 on 2024-06-04 12:39

from django.db import migrations, models
import proco.core.models


class Migration(migrations.Migration):
    dependencies = [
        ('background', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundtask',
            name='deleted',
            field=proco.core.models.CustomDateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backgroundtask',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True,
                                   verbose_name='Task Readable Name'),
        ),
        migrations.AddField(
            model_name='backgroundtask',
            name='name',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Task Unique Name'),
        ),
        migrations.AlterField(
            model_name='backgroundtask',
            name='completed_at',
            field=proco.core.models.CustomDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backgroundtask',
            name='created_at',
            field=proco.core.models.CustomDateTimeField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql="UPDATE background_backgroundtask SET name = task_id",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='backgroundtask',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Task Unique Name'),
        ),
    ]
