# Generated by Django 2.2.28 on 2024-06-04 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('background', '0002_added_name_descritpion_soft_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundtask',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='deleted_backgroundtasks', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Deleted By'),
        ),
    ]
