# Generated by Django 2.2.28 on 2024-12-17 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_check_app', '0001_added_daily_check_models_for_school_master_data_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailycheckapp_schoolstatic',
            old_name='nearest_GSM_distance',
            new_name='nearest_gsm_distance',
        ),
        migrations.RenameField(
            model_name='dailycheckapp_schoolstatic',
            old_name='nearest_LTE_distance',
            new_name='nearest_lte_distance',
        ),
        migrations.RenameField(
            model_name='dailycheckapp_schoolstatic',
            old_name='nearest_NR_distance',
            new_name='nearest_nr_distance',
        ),
        migrations.RenameField(
            model_name='dailycheckapp_schoolstatic',
            old_name='nearest_UMTS_distance',
            new_name='nearest_umts_distance',
        ),
    ]
