# Generated by Django 2.2.28 on 2024-12-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_check_app', '0002_added_daily_check_models_for_school_master_data_source_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckapp_schoolmasterdata',
            name='connectivity_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailycheckapp_schoolmasterdata',
            name='connectivity_type_root',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailycheckapp_schoolstatic',
            name='connectivity_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailycheckapp_schoolstatic',
            name='connectivity_type_root',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
