# Generated by Django 2.2.28 on 2024-12-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_check_app', '0003_added_daily_check_models_for_school_master_data_source_v3'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckapp_schoolstatic',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dailycheckapp_schoolstatic',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
