# Generated by Django 2.2.28 on 2024-01-15 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('locations', '0013_school_master_data_source_changes'),
        ('data_sources', '0001_added_school_master_data_source_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckAppMeasurementData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('browserId', models.TextField(blank=True, null=True)),
                ('school_id', models.TextField()),
                ('giga_id_school', models.TextField(blank=True, null=True)),
                ('download', models.FloatField(blank=True, null=True)),
                ('upload', models.FloatField(blank=True, null=True)),
                ('latency', models.IntegerField(blank=True, null=True)),
                ('country_code', models.TextField(blank=True, null=True)),
                ('ip_address', models.TextField(blank=True, null=True)),
                ('app_version', models.TextField(blank=True, null=True)),
                ('source', models.TextField()),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.RemoveField(
            model_name='historicalschoolmasterdata',
            name='country_iso3_format',
        ),
        migrations.RemoveField(
            model_name='schoolmasterdata',
            name='country_iso3_format',
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='locations.Country'),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='school_master_rows', to='locations.Country'),
        ),
        migrations.AlterField(
            model_name='historicalschoolmasterdata',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'In Draft'), ('UPDATED_IN_DRAFT', 'UPDATED BY EDITOR'),
                                            ('DRAFT_LOCKED', 'ASSIGNED To PUBLISHER'),
                                            ('UPDATED_IN_DRAFT_LOCKED', 'UPDATED BY PUBLISHER'),
                                            ('PUBLISHED', 'Published'), ('DELETED', 'Deleted')], default='DRAFT',
                                   max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolmasterdata',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'In Draft'), ('UPDATED_IN_DRAFT', 'UPDATED BY EDITOR'),
                                            ('DRAFT_LOCKED', 'ASSIGNED To PUBLISHER'),
                                            ('UPDATED_IN_DRAFT_LOCKED', 'UPDATED BY PUBLISHER'),
                                            ('PUBLISHED', 'Published'), ('DELETED', 'Deleted')], default='DRAFT',
                                   max_length=50),
        ),
    ]
