# Generated by Django 2.2.28 on 2024-01-22 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_country_meta_data'),
        ('data_sources', '0002_added_daily_check_app_data_source_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='QoSData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('date', models.DateField()),
                ('school_id_giga', models.CharField(max_length=50)),
                ('school_id_gov', models.CharField(blank=True, max_length=255, null=True)),
                ('speed_download', models.FloatField(blank=True, null=True)),
                ('speed_upload', models.FloatField(blank=True, null=True)),
                ('roundtrip_time', models.FloatField(blank=True, null=True)),
                ('jitter_download', models.FloatField(blank=True, null=True)),
                ('jitter_upload', models.FloatField(blank=True, null=True)),
                ('rtt_packet_loss_pct', models.FloatField(blank=True, null=True)),
                ('latency', models.FloatField(blank=True, null=True)),
                ('provider', models.TextField(blank=True, null=True)),
                ('ip_family', models.IntegerField(blank=True, null=True)),
                ('report_id', models.TextField(blank=True, null=True)),
                ('agent_id', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qos_country_rows', to='locations.Country')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qos_school_rows', to='schools.School', verbose_name='QoS School')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
