# Generated by Django 2.2.28 on 2024-03-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0003_added_qos_data_source_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalschoolmasterdata',
            old_name='num_classroom',
            new_name='num_classrooms',
        ),
        migrations.RenameField(
            model_name='historicalschoolmasterdata',
            old_name='school_id_gov',
            new_name='school_id_govt',
        ),
        migrations.RenameField(
            model_name='schoolmasterdata',
            old_name='num_classroom',
            new_name='num_classrooms',
        ),
        migrations.RenameField(
            model_name='schoolmasterdata',
            old_name='school_id_gov',
            new_name='school_id_govt',
        ),
        migrations.RemoveField(
            model_name='historicalschoolmasterdata',
            name='nearest_NR_id',
        ),
        migrations.RemoveField(
            model_name='schoolmasterdata',
            name='nearest_NR_id',
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='admin1_id_giga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='admin2_id_giga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='admin1_id_giga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='admin2_id_giga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
