# Generated by Django 2.2.28 on 2024-03-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0004_updated_school_master_fields_for_source_response_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalschoolmasterdata',
            name='connectivity_static',
        ),
        migrations.RemoveField(
            model_name='schoolmasterdata',
            name='connectivity_static',
        ),
    ]
