# Generated by Django 2.2.28 on 2024-03-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0005_removed_connectivity_static_from_school_master_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschoolmasterdata',
            name='school_name',
            field=models.CharField(default='Name unknown', max_length=1000),
        ),
        migrations.AlterField(
            model_name='schoolmasterdata',
            name='school_name',
            field=models.CharField(default='Name unknown', max_length=1000),
        ),
    ]
