# Generated by Django 2.2.28 on 2024-03-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0006_increased_school_name_length_to_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qosdata',
            old_name='school_id_gov',
            new_name='school_id_govt',
        ),
    ]
