# Generated by Django 2.2.28 on 2024-04-23 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0007_updated_qos_fields_for_source_response_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckappmeasurementdata',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunSQL(
            sql="UPDATE data_sources_dailycheckappmeasurementdata SET created_at = timestamp",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='dailycheckappmeasurementdata',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
