# Generated by Django 2.2.28 on 2024-05-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0008_added_created_at_field_to_pcdc_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='qosdata',
            name='latency_probe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qosdata',
            name='speed_download_probe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qosdata',
            name='speed_upload_probe',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
