# Generated by Django 2.2.28 on 2024-05-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0028_added_soft_deletion_to_model'),
        ('data_sources', '0009_added_qos_kenya_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qosdata',
            unique_together={('school', 'timestamp')},
        ),
    ]
