# Generated by Django 2.2.28 on 2024-05-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data_sources', '0010_added_unique_constraints_on_qos_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckappmeasurementdata',
            name='country_code',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailycheckappmeasurementdata',
            name='created_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dailycheckappmeasurementdata',
            name='school_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalschoolmasterdata',
            name='school_id_giga',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalschoolmasterdata',
            name='school_id_govt',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalschoolmasterdata',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'In Draft'), ('UPDATED_IN_DRAFT', 'UPDATED BY EDITOR'),
                                            ('DRAFT_LOCKED', 'ASSIGNED To PUBLISHER'),
                                            ('UPDATED_IN_DRAFT_LOCKED', 'UPDATED BY PUBLISHER'),
                                            ('PUBLISHED', 'Published'), ('DELETED', 'Deleted')], db_index=True,
                                   default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='qosdata',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='qosdata',
            name='school_id_giga',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='qosdata',
            name='school_id_govt',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qosdata',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='schoolmasterdata',
            name='school_id_giga',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolmasterdata',
            name='school_id_govt',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolmasterdata',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'In Draft'), ('UPDATED_IN_DRAFT', 'UPDATED BY EDITOR'),
                                            ('DRAFT_LOCKED', 'ASSIGNED To PUBLISHER'),
                                            ('UPDATED_IN_DRAFT_LOCKED', 'UPDATED BY PUBLISHER'),
                                            ('PUBLISHED', 'Published'), ('DELETED', 'Deleted')], db_index=True,
                                   default='DRAFT', max_length=50),
        ),
    ]
