# Generated by Django 2.2.28 on 2024-06-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data_sources', '0011_added_indexes_on_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschoolmasterdata',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'In Draft'), ('UPDATED_IN_DRAFT', 'UPDATED BY EDITOR'),
                                            ('DRAFT_LOCKED', 'ASSIGNED To PUBLISHER'),
                                            ('UPDATED_IN_DRAFT_LOCKED', 'UPDATED BY PUBLISHER'),
                                            ('PUBLISHED', 'Published'), ('DELETED', 'Deleted'),
                                            ('DELETED_PUBLISHED', 'Published Deleted'), ('DISCARDED', 'Discarded')],
                                   db_index=True, default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolmasterdata',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'In Draft'), ('UPDATED_IN_DRAFT', 'UPDATED BY EDITOR'),
                                            ('DRAFT_LOCKED', 'ASSIGNED To PUBLISHER'),
                                            ('UPDATED_IN_DRAFT_LOCKED', 'UPDATED BY PUBLISHER'),
                                            ('PUBLISHED', 'Published'), ('DELETED', 'Deleted'),
                                            ('DELETED_PUBLISHED', 'Published Deleted'), ('DISCARDED', 'Discarded')],
                                   db_index=True, default='DRAFT', max_length=50),
        ),
    ]
