# Generated by Django 2.2.28 on 2024-08-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0012_added_deleted_published_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qosdata',
            name='speed_download_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qosdata',
            name='speed_upload_mean',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
