# Generated by Django 2.2.28 on 2024-10-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0015_added_download_speed_school_benchmark_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='building_id_govt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='num_schools_per_building',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='building_id_govt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='num_schools_per_building',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
