# Generated by Django 2.2.28 on 2025-01-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0016_added_new_school_master_fields_for_honduras_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckappmeasurementdata',
            name='latency',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
