# Generated by Django 2.2.28 on 2025-03-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0017_increased_latency_field_size_for_pcdc'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='education_level_govt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='education_level_govt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
