# Generated by Django 2.2.28 on 2025-05-15 12:37

from django.db import migrations
import proco.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0018_added_school_education_level_govt_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckappmeasurementdata',
            name='pulled_at',
            field=proco.core.models.CustomDateTimeField(blank=True, null=True, verbose_name='Pulled at Date'),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='pulled_at',
            field=proco.core.models.CustomDateTimeField(blank=True, null=True, verbose_name='Pulled at Date'),
        ),
        migrations.AddField(
            model_name='qosdata',
            name='pulled_at',
            field=proco.core.models.CustomDateTimeField(blank=True, null=True, verbose_name='Pulled at Date'),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='pulled_at',
            field=proco.core.models.CustomDateTimeField(blank=True, null=True, verbose_name='Pulled at Date'),
        ),
    ]
