# Generated by Django 2.2.28 on 2025-05-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0019_added_pulled_at_for_all_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='qosdata',
            name='inbound_traffic_sum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qosdata',
            name='is_connected_all',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='qosdata',
            name='is_connected_true',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='qosdata',
            name='latency_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qosdata',
            name='latency_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qosdata',
            name='latency_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qosdata',
            name='outbound_traffic_sum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qosdata',
            name='pe_egress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qosdata',
            name='pe_ingress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qosdata',
            name='signal_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qosdata',
            name='signal_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qosdata',
            name='speed_download_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qosdata',
            name='speed_upload_max',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
