# Generated by Django 2.2.28 on 2026-06-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0019_added_pulled_at_for_all_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='is_verified_school',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='is_verified_school',
            field=models.BooleanField(default=True),
        ),
    ]
