# Generated by Django 2.2.28 on 2026-02-13 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0022_added_disclaimer_field_on_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_sources', '0020_auto_20260213_1705'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhealthentitymasterintermediatedata',
            name='entity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entities.Entity', verbose_name='Health Entity'),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterintermediatedata',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterintermediatedata',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterintermediatedata',
            name='published_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Published By'),
        ),
        migrations.AddField(
            model_name='healthentitymasterintermediatedata',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='health_entity_master_rows', to='locations.Country'),
        ),
        migrations.AddField(
            model_name='healthentitymasterintermediatedata',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='health_master_data', to='entities.Entity', verbose_name='Health Entity'),
        ),
        migrations.AddField(
            model_name='healthentitymasterintermediatedata',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_healthentitymasterintermediatedatas', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AddField(
            model_name='healthentitymasterintermediatedata',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_published_healthentitymasterintermediatedatas', to=settings.AUTH_USER_MODEL, verbose_name='Published By'),
        ),
    ]
