# Generated by Django 2.2.28 on 2025-12-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0021_added_health_entity_master_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='computer_availability',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='connectivity_govt',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='connectivity_govt_collection_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='connectivity_type_govt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='device_availability',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='download_speed_contracted',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='electricity_availability',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='electricity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='facility_data_collection_modality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='facility_data_collection_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='facility_data_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='facility_establishment_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='is_facility_open',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='num_adm_personnel',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='num_computers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='num_tablets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='sustainable_business_model',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='healthentitymasterdata',
            name='water_availability',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='computer_availability',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='connectivity_govt',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='connectivity_govt_collection_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='connectivity_type_govt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='device_availability',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='download_speed_contracted',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='electricity_availability',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='electricity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='facility_data_collection_modality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='facility_data_collection_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='facility_data_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='facility_establishment_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='is_facility_open',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='num_adm_personnel',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='num_computers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='num_tablets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='sustainable_business_model',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterdata',
            name='water_availability',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='computer_availability',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='connectivity_govt',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='connectivity_govt_collection_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='connectivity_type_govt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='device_availability',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='download_speed_contracted',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='electricity_availability',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='electricity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='facility_data_collection_modality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='facility_data_collection_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='facility_data_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='facility_establishment_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='is_facility_open',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='num_adm_personnel',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='num_computers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='num_tablets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='sustainable_business_model',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalschoolmasterdata',
            name='water_availability',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='computer_availability',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='connectivity_govt',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='connectivity_govt_collection_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='connectivity_type_govt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='device_availability',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='download_speed_contracted',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='electricity_availability',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='electricity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='facility_data_collection_modality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='facility_data_collection_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='facility_data_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='facility_establishment_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='is_facility_open',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='num_adm_personnel',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='num_computers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='num_tablets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='sustainable_business_model',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='schoolmasterdata',
            name='water_availability',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
