# Generated by Django 2.2.28 on 2025-11-27 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0021_create_health_models'),
    ]

    operations = [
    ]
