# Generated by Django 2.2.28 on 2026-05-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0021_auto_20260407_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthentitymasterintermediatedata',
            name='facility_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='healthentitymasterintermediatedata',
            name='licensing_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhealthentitymasterintermediatedata',
            name='facility_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhealthentitymasterintermediatedata',
            name='licensing_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
