# Generated by Django 2.2.28 on 2026-02-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0021_auto_20260213_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthentitymasterintermediatedata',
            name='facility_id_govt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhealthentitymasterintermediatedata',
            name='facility_id_govt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
