# Generated by Django 2.2.28 on 2026-05-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0022_auto_20260511_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthentitymasterintermediatedata',
            name='hmis_system',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhealthentitymasterintermediatedata',
            name='hmis_system',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
