# Generated by Django 2.2.28 on 2026-07-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0024_auto_20260626_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthentitymasterintermediatedata',
            name='coverage_type',
            field=models.CharField(blank=True, default='unknown', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalhealthentitymasterintermediatedata',
            name='coverage_type',
            field=models.CharField(blank=True, default='unknown', max_length=255, null=True),
        ),
    ]
